In [15]:
import numpy as np 
array1 = np.array([[2,3,5],[1,2,3],[5,2,1]])
array2 = np.array([[1,3,2],[4,2,5],[6,3,1]])
print("Array1:") 
print(array1)
print("Array2:") 
print(array2)
print("\nafter multiplication:")
print(np.multiply(array1,array2))


Array1:
[[2 3 5]
 [1 2 3]
 [5 2 1]]
Array2:
[[1 3 2]
 [4 2 5]
 [6 3 1]]

after multiplication:
[[ 2  9 10]
 [ 4  4 15]
 [30  6  1]]
