In [2]:
import numpy as np
x = np.array([[0,1,4],[2,3,5]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))


Original array:
[[0 1 4]
 [2 3 5]]
Sum of all elements:
15
Sum of each column:
[2 4 9]
Sum of each row:
[ 5 10]
